version: '3.9'
services:
  php:
    image: ghcr.io/fransfilastap/bphn-masjid-screen:latest
    environment:
      - APP_URL=http://localhost:${PORT:-8080}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - "db:/app/db:rw"
      - "wallpaper:/app/display/wallpaper:rw"
volumes:
  db:
    external: false
  wallpaper:
    external: false

