version: '3.9'
services:
  php:
    image: webdevops/php-nginx-dev:8.0
    working_dir: /app
    environment:
      - APP_URL=${APP_URL}
      - WEB_DOCUMENT_ROOT=/app/
      - PHP_DISPLAY_ERRORS=0
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_MAX_NESTING_LEVEL=1000
    ports:
      - "8080:80"
    volumes:
      - ./app:/app:rw,cached