version: '3.9'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_URL=http://localhost:8080
    ports:
      - "8080:8080"
    volumes:
      - "db:/app/db:rw"
      - "wallpaper:/app/display/wallpaper:rw"
volumes:
  db:
    external: false
  wallpaper:
    external: false

