version: "3.9"
services:
  nginx_default:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
  php_default:
    image: ffilasta/bphn-mosque-screen
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log
    environment:
      APP_URL: ${APP_URL}

