version: "3.9"
services:
  nginx_default:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
    networks:
      - internal
  php_default:
    build:
      context: .
      dockerfile: php/Dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log
    networks:
      - internal
networks:
  internal:
    driver: bridge

